<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 2017/9/2
 * Time: 12:11
 */
namespace framework\web;

abstract class Api extends Controller
{
    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $urlComponent = $this->getComponent('response');
        $urlComponent->noCache();
        $urlComponent->contentType('json');
        unset($urlComponent);
    }

    protected function assign($key, $value = null)
    {
        unset($value);
    }

    protected function display($path = '')
    {
        return '';
    }

    public function afterAction($data = array()): array
    {
        if (!is_array($data))
        {
            $data = array($data);
        }
        return $data;
    }
}