<?php
/**
 * Created by PhpStorm.
 * User: rxw
 * Date: 2017/9/2
 * Time: 12:11
 */
namespace framework\web;

abstract class Controller extends \framework\base\Controller
{
    protected function isAjax()
    {
        $server = $this->getComponent('url')->getServer();
        $result = isset($server['HTTP_X_REQUESTED_WITH']) && $server['HTTP_X_REQUESTED_WITH']==='XMLHttpRequest';
        unset($server);
        return $result;
    }

    protected function assign($key, $value = null)
    {
        $this->getComponent('view')->assign($key, $value);
    }

    protected function display($path = '')
    {
        return $this->getComponent('view')->display($path);
    }

    protected function ajax($data,$status=true,$msg='')
    {
        $data = array('ret' => $status, 'msg' => $msg, 'data' => $data);
        return parent::ajax($data); // TODO: Change the autogenerated stub
    }

    protected function getSession()
    {
        return $this->getComponent('session');
    }

    protected function getCache()
    {
        return $this->getComponent('cache');
    }

    protected function getPage()
    {
        return $this->getComponent('page');
    }
}